# Generated by Django 4.2.2 on 2023-06-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('guild_id', models.BigIntegerField()),
                ('connect_time', models.DateTimeField(auto_now_add=True)),
                ('disconnect_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
