# Generated by Django 4.2.2 on 2023-06-18 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceactivity',
            name='connect_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
