# Generated by Django 4.2.2 on 2023-06-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeconfig',
            name='guild_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
